import React from 'react'
export const columns = [
  {
    title: '商品编号',
    dataIndex: 'shopNum',
    render: text => <a>{text}</a>,
  },
  {
    title: '商品名称',
    dataIndex: 'shopName',
  },
  {
    title: '商品价格',
    dataIndex: 'shopPrice',
  },
  {
    title: '打折力度',
    dataIndex: 'Count',
  },
  {
    title: '折后价格',
    dataIndex: 'CountPrice',
  },
]

export const data = [
  {
    key: '1',
    shopNum: 'A-001',
    shopName: '清风餐巾纸',
    shopPrice: '￥15',
    Count: '15%',
    CountPrice: '￥8',
  },
  {
    key: '2',
    shopNum: 'A-001',
    shopName: '清风餐巾纸',
    shopPrice: '￥15',
    Count: '15%',
    CountPrice: '￥8',
  },
  {
    key: '3',
    shopNum: 'A-001',
    shopName: '清风餐巾纸',
    shopPrice: '￥15',
    Count: '15%',
    CountPrice: '￥8',
  },
  {
    key: '4',
    shopNum: 'A-002',
    shopName: '清风餐巾纸',
    shopPrice: '￥15',
    Count: '15%',
    CountPrice: '￥8',
  },
  {
    key: '5',
    shopNum: 'A-002',
    shopName: '清风餐巾纸',
    shopPrice: '￥15',
    Count: '15%',
    CountPrice: '￥8',
  },
  {
    key: '6',
    shopNum: 'A-002',
    shopName: '清风餐巾纸',
    shopPrice: '￥15',
    Count: '15%',
    CountPrice: '￥8',
  },
  {
    key: '7',
    shopNum: 'A-003',
    shopName: '清风餐巾纸',
    shopPrice: '￥15',
    Count: '15%',
    CountPrice: '￥8',
  },
  {
    key: '8',
    shopNum: 'A-003',
    shopName: '清风餐巾纸',
    shopPrice: '￥15',
    Count: '15%',
    CountPrice: '￥8',
  },
  {
    key: '9',
    shopNum: 'A-004',
    shopName: '清风餐巾纸',
    shopPrice: '￥15',
    Count: '15%',
    CountPrice: '￥8',
  },
  {
    key: '10',
    shopNum: 'A-005',
    shopName: '清风餐巾纸',
    shopPrice: '￥15',
    Count: '15%',
    CountPrice: '￥8',
  },
  {
    key: '11',
    shopNum: 'A-006',
    shopName: '清风餐巾纸',
    shopPrice: '￥15',
    Count: '15%',
    CountPrice: '￥8',
  },
  {
    key: '12',
    shopNum: 'A-007',
    shopName: '清风餐巾纸',
    shopPrice: '￥15',
    Count: '15%',
    CountPrice: '￥8',
  },
]